#!/usr/bin/env python3
"""
Distribution Classifier — Distribute findings to channels.

Takes a classified report and routes findings to GitHub issues,
Slack alerts, or local report entries.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Distribute classified findings to channels")
    parser.add_argument("classified_report", type=Path, help="Path to classified JSON report")
    parser.add_argument("--channels", "-c", nargs="+",
                        choices=["github", "slack", "email", "report", "all"],
                        default=["report"], help="Target channels")
    parser.add_argument("--severity", "-s", nargs="+",
                        choices=["critical", "high", "medium", "low", "info"],
                        help="Filter by severity (default: all)")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be sent")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if not args.classified_report.exists():
        print(f"[!] Classified report not found: {args.classified_report}")
        return 1

    findings = json.loads(args.classified_report.read_text(encoding="utf-8"))
    if not isinstance(findings, list):
        findings = [findings]

    # Filter by severity
    if args.severity:
        findings = [f for f in findings if f.get("severity", "").lower() in args.severity]

    # Resolve channels
    channels = args.channels
    if "all" in channels:
        channels = ["github", "slack", "email", "report"]

    print(f"[Distribution Router] Distributing {len(findings)} findings to: {', '.join(channels)}")
    print()

    # Filter findings by requested channels
    channel_findings: dict[str, list] = {ch: [] for ch in channels}
    for f in findings:
        finding_channels = f.get("channels", ["report"])
        for ch in channels:
            if ch in finding_channels:
                channel_findings[ch].append(f)

    # Route to each channel
    for channel, items in channel_findings.items():
        if not items:
            continue
        print(f"  [{channel.upper()}] {len(items)} finding(s)")

        if args.dry_run:
            for item in items:
                print(f"    Would send: [{item['severity'].upper()}] {item['title']}")
            continue

        if channel == "github":
            _distribute_github(items)
        elif channel == "slack":
            _distribute_slack(items)
        elif channel == "email":
            _distribute_email(items)
        elif channel == "report":
            _distribute_report(items, args.classified_report)

    print(f"\n  [OK] Distribution complete")
    return 0


def _distribute_github(findings: list[dict]) -> None:
    """Create GitHub issues for findings (simulated — uses gh CLI if available)."""
    import subprocess
    for f in findings:
        title = f"[SECURITY] [{f['severity'].upper()}] {f['title']}"
        body = (
            f"## Vulnerability Report\n\n"
            f"**Brand:** {f.get('brand', 'N/A')}\n"
            f"**Severity:** {f['severity'].upper()}\n"
            f"**Category:** {f.get('category', 'N/A')}\n"
            f"**Location:** `{f.get('location', 'N/A')}`\n"
            f"**Fixable:** {f.get('fixable', False)}\n\n"
            f"### Description\n{f.get('description', 'N/A')}\n\n"
            f"### Remediation\n{f.get('remediation', 'N/A')}\n\n"
            f"---\n*Auto-generated by SaaS-Security-Auditor*"
        )
        print(f"    Creating GitHub issue: {title[:60]}...")
        # Try gh CLI if available
        try:
            import subprocess
            result = subprocess.run(
                ["gh", "issue", "create", "--title", title, "--body", body, "--label", f"security,{f['severity']}"],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode == 0:
                print(f"    [OK] Issue created: {result.stdout.strip()}")
            else:
                print(f"    [!] gh CLI failed: {result.stderr[:200]}")
        except (FileNotFoundError, subprocess.TimeoutExpired) as e:
            print(f"    [!] Could not create issue (gh not available): {e}")
            # Fallback: save as local file
            issues_dir = Path("output/distributions/github_issues")
            issues_dir.mkdir(parents=True, exist_ok=True)
            safe_title = "".join(c for c in title if c.isalnum() or c in " -_").strip()[:50]
            (issues_dir / f"{safe_title}.md").write_text(body, encoding="utf-8")
            print(f"    [OK] Issue saved locally: {issues_dir / safe_title}.md")


def _distribute_slack(findings: list[dict]) -> None:
    """Send Slack alert (dummy — requires SLACK_WEBHOOK_URL)."""
    webhook = None  # In production, read from env
    for f in findings:
        if f["severity"] in ("critical", "high"):
            print(f"    [SLACK] CRITICAL alert: {f['title']}")
            print(f"    [SLACK] Would send to #security-alerts channel")
            # In production:
            # import requests
            # requests.post(webhook, json={"text": alert_text})


def _distribute_email(findings: list[dict]) -> None:
    """Send email alert (dummy)."""
    for f in findings:
        print(f"    [EMAIL] Would email security team about: {f['title']}")


def _distribute_report(findings: list[dict], report_path: Path) -> None:
    """Generate a distribution manifest."""
    dist_dir = Path("output/distributions")
    dist_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "source_report": str(report_path),
        "distributed_at": datetime.now(timezone.utc).isoformat(),
        "total_findings": len(findings),
        "by_severity": {},
        "findings": findings,
    }
    for f in findings:
        sev = f.get("severity", "unknown")
        manifest["by_severity"][sev] = manifest["by_severity"].get(sev, 0) + 1

    out = dist_dir / f"distribution-{datetime.now().strftime('%Y%m%d-%H%M%S')}.json"
    out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"    [REPORT] Distribution manifest: {out}")


if __name__ == "__main__":
    exit(main())
